# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class SearchRequestMinShouldMatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mutation': 'int',
        'gene': 'int'
    }

    attribute_map = {
        'mutation': 'MUTATION',
        'gene': 'GENE'
    }

    def __init__(self, mutation=None, gene=None):  # noqa: E501
        """SearchRequestMinShouldMatch - a model defined in Swagger"""  # noqa: E501
        self._mutation = None
        self._gene = None
        self.discriminator = None
        if mutation is not None:
            self.mutation = mutation
        if gene is not None:
            self.gene = gene

    @property
    def mutation(self):
        """Gets the mutation of this SearchRequestMinShouldMatch.  # noqa: E501


        :return: The mutation of this SearchRequestMinShouldMatch.  # noqa: E501
        :rtype: int
        """
        return self._mutation

    @mutation.setter
    def mutation(self, mutation):
        """Sets the mutation of this SearchRequestMinShouldMatch.


        :param mutation: The mutation of this SearchRequestMinShouldMatch.  # noqa: E501
        :type: int
        """

        self._mutation = mutation

    @property
    def gene(self):
        """Gets the gene of this SearchRequestMinShouldMatch.  # noqa: E501


        :return: The gene of this SearchRequestMinShouldMatch.  # noqa: E501
        :rtype: int
        """
        return self._gene

    @gene.setter
    def gene(self, gene):
        """Sets the gene of this SearchRequestMinShouldMatch.


        :param gene: The gene of this SearchRequestMinShouldMatch.  # noqa: E501
        :type: int
        """

        self._gene = gene

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchRequestMinShouldMatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchRequestMinShouldMatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
