# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mm_power_sdk_python
from api.clinical_trials_api import ClinicalTrialsApi  # noqa: E501
from mm_power_sdk_python.rest import ApiException


class TestClinicalTrialsApi(unittest.TestCase):
    """ClinicalTrialsApi unit test stubs"""

    def setUp(self):
        self.api = api.clinical_trials_api.ClinicalTrialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_trials(self):
        """Test case for count_trials

        Get the count of Clinical Trials matching a searchRequest  # noqa: E501
        """
        pass

    def test_search_trials(self):
        """Test case for search_trials

        Search for clinical trials  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
