# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mm_power_sdk_python
from api.clinical_trial_api import ClinicalTrialApi  # noqa: E501
from mm_power_sdk_python.rest import ApiException


class TestClinicalTrialApi(unittest.TestCase):
    """ClinicalTrialApi unit test stubs"""

    def setUp(self):
        self.api = api.clinical_trial_api.ClinicalTrialApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_trial(self):
        """Test case for get_trial

        Get a Clinical Trial  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
