# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.clinical_trial_eligibility import ClinicalTrialEligibility  # noqa: E501
from swagger_client.rest import ApiException


class TestClinicalTrialEligibility(unittest.TestCase):
    """ClinicalTrialEligibility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClinicalTrialEligibility(self):
        """Test ClinicalTrialEligibility"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.clinical_trial_eligibility.ClinicalTrialEligibility()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
