# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.drug_parents import DrugParents  # noqa: E501
from swagger_client.rest import ApiException


class TestDrugParents(unittest.TestCase):
    """DrugParents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDrugParents(self):
        """Test DrugParents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.drug_parents.DrugParents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
