# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mm_power_sdk_python
from models.expanded_access import ExpandedAccess  # noqa: E501
from mm_power_sdk_python.rest import ApiException


class TestExpandedAccess(unittest.TestCase):
    """ExpandedAccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExpandedAccess(self):
        """Test ExpandedAccess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mm_power_sdk_python.models.expanded_access.ExpandedAccess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
