# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.sponsor import Sponsor  # noqa: E501
from swagger_client.rest import ApiException


class TestSponsor(unittest.TestCase):
    """Sponsor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSponsor(self):
        """Test Sponsor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sponsor.Sponsor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
