# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mm_power_sdk_python
from models.clinical_trial_synonyms import ClinicalTrialSynonyms  # noqa: E501
from mm_power_sdk_python.rest import ApiException


class TestClinicalTrialSynonyms(unittest.TestCase):
    """ClinicalTrialSynonyms unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClinicalTrialSynonyms(self):
        """Test ClinicalTrialSynonyms"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mm_power_sdk_python.models.clinical_trial_synonyms.ClinicalTrialSynonyms()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
