# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ClinicalTrialLeadSponsor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agency': 'str',
        'agency_class': 'list[str]'
    }

    attribute_map = {
        'agency': 'agency',
        'agency_class': 'agency_class'
    }

    def __init__(self, agency=None, agency_class=None):  # noqa: E501
        """ClinicalTrialLeadSponsor - a model defined in Swagger"""  # noqa: E501
        self._agency = None
        self._agency_class = None
        self.discriminator = None
        self.agency = agency
        if agency_class is not None:
            self.agency_class = agency_class

    @property
    def agency(self):
        """Gets the agency of this ClinicalTrialLeadSponsor.  # noqa: E501


        :return: The agency of this ClinicalTrialLeadSponsor.  # noqa: E501
        :rtype: str
        """
        return self._agency

    @agency.setter
    def agency(self, agency):
        """Sets the agency of this ClinicalTrialLeadSponsor.


        :param agency: The agency of this ClinicalTrialLeadSponsor.  # noqa: E501
        :type: str
        """
        if agency is None:
            raise ValueError("Invalid value for `agency`, must not be `None`")  # noqa: E501

        self._agency = agency

    @property
    def agency_class(self):
        """Gets the agency_class of this ClinicalTrialLeadSponsor.  # noqa: E501


        :return: The agency_class of this ClinicalTrialLeadSponsor.  # noqa: E501
        :rtype: list[str]
        """
        return self._agency_class

    @agency_class.setter
    def agency_class(self, agency_class):
        """Sets the agency_class of this ClinicalTrialLeadSponsor.


        :param agency_class: The agency_class of this ClinicalTrialLeadSponsor.  # noqa: E501
        :type: list[str]
        """

        self._agency_class = agency_class

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClinicalTrialLeadSponsor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClinicalTrialLeadSponsor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
