# coding: utf-8

"""
    MolecularMatch MMPower

    MMPower API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@molecularmatch.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class MongoTrialSynonyms(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'suppress': 'bool',
        'custom': 'bool',
        'ctlink': 'bool',
        'name': 'str',
        'analyzer': 'str'
    }

    attribute_map = {
        'suppress': 'suppress',
        'custom': 'custom',
        'ctlink': 'ctlink',
        'name': 'name',
        'analyzer': 'analyzer'
    }

    def __init__(self, suppress=None, custom=None, ctlink=None, name=None, analyzer='DEFAULT'):  # noqa: E501
        """MongoTrialSynonyms - a model defined in Swagger"""  # noqa: E501
        self._suppress = None
        self._custom = None
        self._ctlink = None
        self._name = None
        self._analyzer = None
        self.discriminator = None
        if suppress is not None:
            self.suppress = suppress
        if custom is not None:
            self.custom = custom
        if ctlink is not None:
            self.ctlink = ctlink
        self.name = name
        if analyzer is not None:
            self.analyzer = analyzer

    @property
    def suppress(self):
        """Gets the suppress of this MongoTrialSynonyms.  # noqa: E501


        :return: The suppress of this MongoTrialSynonyms.  # noqa: E501
        :rtype: bool
        """
        return self._suppress

    @suppress.setter
    def suppress(self, suppress):
        """Sets the suppress of this MongoTrialSynonyms.


        :param suppress: The suppress of this MongoTrialSynonyms.  # noqa: E501
        :type: bool
        """

        self._suppress = suppress

    @property
    def custom(self):
        """Gets the custom of this MongoTrialSynonyms.  # noqa: E501


        :return: The custom of this MongoTrialSynonyms.  # noqa: E501
        :rtype: bool
        """
        return self._custom

    @custom.setter
    def custom(self, custom):
        """Sets the custom of this MongoTrialSynonyms.


        :param custom: The custom of this MongoTrialSynonyms.  # noqa: E501
        :type: bool
        """

        self._custom = custom

    @property
    def ctlink(self):
        """Gets the ctlink of this MongoTrialSynonyms.  # noqa: E501


        :return: The ctlink of this MongoTrialSynonyms.  # noqa: E501
        :rtype: bool
        """
        return self._ctlink

    @ctlink.setter
    def ctlink(self, ctlink):
        """Sets the ctlink of this MongoTrialSynonyms.


        :param ctlink: The ctlink of this MongoTrialSynonyms.  # noqa: E501
        :type: bool
        """

        self._ctlink = ctlink

    @property
    def name(self):
        """Gets the name of this MongoTrialSynonyms.  # noqa: E501


        :return: The name of this MongoTrialSynonyms.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MongoTrialSynonyms.


        :param name: The name of this MongoTrialSynonyms.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def analyzer(self):
        """Gets the analyzer of this MongoTrialSynonyms.  # noqa: E501


        :return: The analyzer of this MongoTrialSynonyms.  # noqa: E501
        :rtype: str
        """
        return self._analyzer

    @analyzer.setter
    def analyzer(self, analyzer):
        """Sets the analyzer of this MongoTrialSynonyms.


        :param analyzer: The analyzer of this MongoTrialSynonyms.  # noqa: E501
        :type: str
        """
        allowed_values = ["DEFAULT", "CASE_SENSITIVE"]  # noqa: E501
        if analyzer not in allowed_values:
            raise ValueError(
                "Invalid value for `analyzer` ({0}), must be one of {1}"  # noqa: E501
                .format(analyzer, allowed_values)
            )

        self._analyzer = analyzer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MongoTrialSynonyms, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MongoTrialSynonyms):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
